name: Reusable Workflow

on:
  workflow_call:
    inputs:
      file_path:
        description: 'Path to the file to modify'
        required: true
        type: string

jobs:
  change-tag:
    uses: ./.github/workflows/change-tag.yml
    with:
      file_path: ${{ inputs.file_path }}

